In [25]:
import pandas as pdcontent
df=pd.read_csv('/amazon data set.csv')
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th..."

Understand the Dataset

In [35]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1400 entries, 0 to 1464
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1400 non-null   object
 1   product_name         1400 non-null   object
 2   category             1400 non-null   object
 3   discounted_price     1400 non-null   float64
 4   actual_price         1400 non-null   float64
 5   discount_percentage  1400 non-null   object
 6   rating               1399 non-null   float64
 7   rating_count         1398 non-null   object
 8   about_product        1400 non-null   object
 9   user_id              1400 non-null   object
 10  user_name            1400 non-null   object
 11  review_id            1400 non-null   object
 12  review_title         1400 non-null   object
 13  review_content       1400 non-null   object
dtypes: float64(3), object(11)
memory usage: 164.1+ KB

       discounted_price   actual_price       rating
count       1400.000000    1400.000000  1399.000000
mean        3229.772000    5613.668771     4.093352
std         7069.037471   11064.372508     0.294086
min           39.000000      39.000000     2.000000
25%          344.000000     899.000000     4.000000
50%          849.500000    1699.000000     4.100000
75%         2096.000000    4612.500000     4.300000
max        77990.000000  139900.000000     5.000000

Perform initial data cleaning:

check missing values

In [36]:
df.isnull().sum()
df.dropna(inplace=True)

remove duplicate rows

In [37]:
df.drop_duplicates(inplace=True)

check column names

In [38]:
print(df.columns)

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content'],
      dtype='object')

clean the column (if any spaces)

In [39]:
df.columns=df.columns.str.strip()

convert the column to numeric first:

In [45]:
df['discounted_price']=(
df['discounted_price']
.replace('[₹,]','',regex=True)
.astype(float)
)
df['actual_price']=(
    df['actual_price']
    .replace('[₹,]','',regex=True)
    .astype(float)
)
df['discount_percentage']=(
    df['discount_percentage']
    .replace('%','',regex=True)
    .astype(float)
)

if rating is object/string:

In [41]:
df['rating']=pd.to_numeric(df['rating'],errors='coerce')

Question 1:
which product catagories have the highest ratings?

In [42]:
df.groupby('category')['rating'].mean().sort_values(ascending=False)

category
Computers&Accessories|Tablets                                                                                    4.6
Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters                                         4.5
Electronics|Cameras&Photography|Accessories|Film                                                                 4.5
Computers&Accessories|Components|Memory                                                                          4.5
Electronics|HomeAudio|MediaStreamingDevices|StreamingClients                                                     4.5
                                                                                                                ...
Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones                               3.6
Electronics|HomeTheater,TV&Video|Accessories|3DGlasses                                                           3.5
Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets                                  3.5
Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers    3.4
Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders                          3.3
Name: rating, Length: 211, dtype: float64

Question 2:
which product has the highest discounts?

In [43]:
df[['product_name','discount_percentage']].sort_values(by='discount_percentage',ascending=False).head(10)

                                          product_name discount_percentage
695  rts [2 Pack] Mini USB C Type C Adapter Plug, T...                 94%
372  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...                 91%
380  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...                 91%
364  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...                 91%
334  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...                 91%
368  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...                 91%
542  Sounce Protective Case Cover Compatible Boat X...                 90%
2    Sounce Fast Phone Charging Cable & Data Sync U...                 90%
602  LAPSTER Spiral Charger Spiral Charger Cable Pr...                 90%
557  LAPSTER 12pcs Spiral Cable Protectors for Char...                 90%

Question 3:
is there relationship between rating and percentage?

In [46]:
df[['rating','discount_percentage']].corr()

                       rating  discount_percentage
rating               1.000000            -0.161384
discount_percentage -0.161384             1.000000

Question 4:
which categories contain the most product?

In [47]:
df['category'].value_counts()

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                                          183
Electronics|WearableTechnology|SmartWatches                                                                                 76
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                                        68
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                                               61
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                                                52
                                                                                                                          ...
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers                                                        1
Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories                                               1
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers                                                       1
Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans                                                                    1
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags      1
Name: count, Length: 211, dtype: int64

Question 5:
what are the top rated products?

In [48]:
df[['product_name','rating']].sort_values(by='rating',ascending=False).head(10)

                                           product_name  rating
174   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
775   Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
1299  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
1201  Oratech Coffee Frother electric, milk frother ...     4.8
1145  Swiffer Instant Electric Water Heater Faucet T...     4.8
1275  Multifunctional 2 in 1 Electric Egg Boiling St...     4.7
1226  Zuvexa USB Rechargeable Electric Foam Maker - ...     4.7
459   Spigen EZ Fit Tempered Glass Screen Protector ...     4.7
1223  FIGMENT Handheld Milk Frother Rechargeable, 3-...     4.7
1388  Campfire Spring Chef Prolix Instant Portable W...     4.7